directories:
  output: dist-electron
  buildResources: build
appId: com.hardplotcafe.thermal-printer
productName: Hard Plot Cafe Thermal Printer
files:
  - filter:
      - dist/**/*
      - electron/**/*
      - node_modules/**/*
mac:
  category: public.app-category.business
  target:
    - target: dmg
      arch:
        - x64
        - arm64
win:
  target:
    - target: nsis
      arch:
        - x64
        - ia32
linux:
  target:
    - target: AppImage
      arch:
        - x64
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
electronVersion: 38.2.0
